baseurl = "/"
languageCode = "en-us"
title = "CSS"

[params]
  description = "Please come visit"

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1
[[menu.main]]
    name = "Hostesses"
    url  = "/hostesses"
    weight = 2